COLOR_BG = "#000000"
COLOR_ACCENT = "#00FFA3"
COLOR_PANEL = "#1A1A1A"
COLOR_PANEL_BORDER = COLOR_ACCENT
COLOR_TEXT = "#FFFFFF"
COLOR_TEXT_MUTED = "#888888"

FONT_FAMILY_BOLD = "'Lexend Bold'"
FONT_FAMILY_REGULAR = "'Lexend Regular'"

